### ISSUE TITLE
couplings desync on server

### ISSUE THREAD

**Issue by Skeithh** [InsomniaKitten/Couplings#29]
Ever since we updated our server from 1.18.1 to 1.18.2, meaning we're now using couplings 1.8.1, We've had desync problem with doors and objects that act like doors in the server. Removing couplings fixed this issue. 
The specific error we receive on client side only when interacting with doors or door-like objects is the following

```
Error executing task on Client
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2680.method_26204()" because "$$1" is null
    at net.minecraft.class_1937.method_30092(class_1937.java:210)
    at net.minecraft.class_1937.method_8652(class_1937.java:196)
    at net.minecraft.class_634.method_34007(class_634.java:650)
    at net.minecraft.class_2637.method_30621(class_2637.java:72)
    at net.minecraft.class_634.method_11100(class_634.java:650)
    at net.minecraft.class_2637.method_11392(class_2637.java:64)
    at net.minecraft.class_2637.method_11054(class_2637.java:14)
    at net.minecraft.class_2600.method_11072(class_2600.java:22)
    at net.minecraft.class_1255.method_18859(class_1255.java:157)
    at net.minecraft.class_4093.method_18859(class_4093.java:23)
    at net.minecraft.class_1255.method_16075(class_1255.java:131)
    at net.minecraft.class_1255.method_5383(class_1255.java:116)
    at net.minecraft.class_310.method_1523(class_310.java:1085)
    at net.minecraft.class_310.method_1514(class_310.java:737)
    at net.minecraft.client.main.Main.main(Main.java:236)
    at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
    at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
    at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by Skeithh** [comment]
nevermind. thought we identified it being couplings but apparently not, sorry!
