### ISSUE TITLE
Unknown Crash Due To Couplings

### ISSUE THREAD

**Issue by CharaViolet** [InsomniaKitten/Couplings#44]
Couplings seems to be crashing my game, but I can't quite understand why, so I figured it'd be best to report it here. I have two crash reports, and have verified that disabling Couplings fixes the issue.
[crash-2024-12-12_18.55.44-client.txt](https://github.com/user-attachments/files/18118057/crash-2024-12-12_18.55.44-client.txt)
[crash-2024-12-12_19.04.26-client.txt](https://github.com/user-attachments/files/18118058/crash-2024-12-12_19.04.26-client.txt)

**Comment by duskingtide** [comment]
Came here to post the exact same crash. Seems to be this snippet which identifies the issue:

>	Caused by: java.lang.UnsupportedOperationException: StampedConfig does not support valueMap() yet.
> 	at knot//com.electronwill.nightconfig.core.concurrent.StampedConfig.valueMap(StampedConfig.java:473)
> 	at knot//com.electronwill.nightconfig.core.utils.UnmodifiableConfigWrapper.valueMap(UnmodifiableConfigWrapper.java:29)
> 	at knot//com.electronwill.nightconfig.core.ConfigSpec.correct(ConfigSpec.java:630)
> 	at knot//com.electronwill.nightconfig.core.ConfigSpec.correct(ConfigSpec.java:618)
> 	at knot//dev.sapphic.couplings.Couplings.<clinit>(Couplings.java:68)
