### ISSUE TITLE
[Crash on Launch] Please update the mod for latest fabric loader

### ISSUE THREAD

**Issue by mlengka93** [InsomniaKitten/Couplings#7]
[09:49:35] [main/INFO]: Loading for game Minecraft 1.14.4
Exception in thread "main" java.lang.RuntimeException: Failed to resolve mods!
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:159)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:122)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: net.fabricmc.loader.discovery.ModResolutionException: Could not resolve valid mod collection (at: couplings requires {fabricloader @ [>=0.4.1 <0.5.0]})
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:184)
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:508)
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:157)
	... 2 more
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81)
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401)
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:182)
	... 4 more
Process exited with code 1.

**Comment by SDUBZ** [comment]
[crash-2019-08-20_20.09.28-client.txt](https://github.com/InsomniaKitten/Couplings/files/3550865/crash-2019-08-20_20.09.28-client.txt)
@mlengka93

**Comment by SDUBZ** [comment]
@mlengka93 i found a temp fix until mod dev can fix it themselves open couplings jar file with winrar etc and edit fabric.mod.json and change "depends":{"fabricloader":">=0.4.1 <0.5.0"}, to this "depends":{"fabricloader":">=0.6.0 <0.7.0"},

**Comment by Prospector** [comment]
just remove the upper bound entirely. it shouldn't be there, no idea why it's there in the first place

**Comment by InsomniaKitten** [comment]
https://github.com/InsomniaKitten/Couplings/commit/ea614aa4cd4edd64ddba9c3df665ce88f4e1b70b
